# Generated by Django 2.2.10 on 2020-11-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201118_1746'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marker_set',
            field=models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to='core.Marker'),
        ),
    ]
