# Generated by Django 2.2.10 on 2020-11-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_marker_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marker_set',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Marker'),
        ),
    ]
