# Generated by Django 2.2.10 on 2020-11-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201118_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='marker_set',
        ),
    ]
