# Generated by Django 2.2.10 on 2020-11-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200220_1425'),
        ('core', '0004_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='augmented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Object'),
        ),
    ]
