# Generated by Django 2.2.10 on 2020-11-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('patt', models.CharField(default='hiro', max_length=50)),
                ('gif', models.CharField(default='peixe', max_length=50)),
                ('scale', models.CharField(default='1 1', max_length=50)),
                ('position', models.CharField(default='0 0 0', max_length=50)),
                ('rotation', models.CharField(default='270 0 0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='markers/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=60)),
                ('title', models.CharField(default='', max_length=60)),
                ('patt', models.FileField(upload_to='patts/')),
            ],
        ),
    ]
