# Generated by Django 2.2.10 on 2020-11-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='markers', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='artworks',
            field=models.ManyToManyField(related_name='exhibits', to='users.Artwork'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exhibits', to='users.Profile'),
        ),
    ]
