# Generated by Django 2.2.10 on 2020-11-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201118_1852'),
        ('core', '0003_auto_20200213_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FileField(upload_to='objects/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=60)),
                ('title', models.CharField(default='', max_length=60)),
                ('scale', models.CharField(default='1 1', max_length=50)),
                ('position', models.CharField(default='0 0 0', max_length=50)),
                ('rotation', models.CharField(default='270 0 0', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='objects', to='users.Profile')),
            ],
        ),
    ]
